package com.example.backend.service;

import com.example.backend.model.DictionaryResponse;
import org.springframework.stereotype.Service;
import java.util.*;

/**
 * DictionaryEntryService provides curated dictionary entries with explanations and pronunciations.
 * This service stores verified dictionary entries for specific Malay-Mandarin word pairs.
 */
@Service
public class DictionaryEntryService {
    
    // Stores curated dictionary entries with full details
    private static final Map<String, DictionaryEntry> DICTIONARY_ENTRIES = new HashMap<>();
    
    // Fallback entries when AI service is unavailable
    private static final Map<String, DictionaryEntry> FALLBACK_ENTRIES = new HashMap<>();
    
    // Stores pronunciation and adjective overrides for specific words
    private static final Map<String, Map<String, Object>> WORD_OVERRIDES = new HashMap<>();
    
    public static class DictionaryEntry {
        private String malayWord;
        private String mandarinWord;
        private String pronunciation;
        private String explanation;
        private String[] examples;
        private boolean isAdjective;
        
        public DictionaryEntry(String malayWord, String mandarinWord, String pronunciation, 
                             String explanation, String[] examples, boolean isAdjective) {
            this.malayWord = malayWord;
            this.mandarinWord = mandarinWord;
            this.pronunciation = pronunciation;
            this.explanation = explanation;
            this.examples = examples;
            this.isAdjective = isAdjective;
        }
        
        // Getters
        public String getMalayWord() { return malayWord; }
        public String getMandarinWord() { return mandarinWord; }
        public String getPronunciation() { return pronunciation; }
        public String getExplanation() { return explanation; }
        public String[] getExamples() { return examples; }
        public boolean isAdjective() { return isAdjective; }
    }
    
    static {
        initializeDictionary();
        initializeFallbackEntries();
    }
    
    private static void initializeDictionary() {
        // All words will be auto-generated by AI using LibreTranslate + DeepseekAI
        // No curated entries maintained
    }
    
    private static void initializeFallbackEntries() {
        // Fallback entry for "sedap" when AI service is unavailable
        FALLBACK_ENTRIES.put("sedap", new DictionaryEntry(
            "sedap",
            "美味",
            "měiwèi",
            "'美味' (měiwèi) bermaksud sesuatu yang mempunyai rasa yang enak, sedap, atau sedap di tekak. Ia menggambarkan makanan atau minuman yang mempunyai citarasa yang tinggi dan dikesan baik oleh penderma.",
            new String[]{
                "1. 我们今天晚上想吃一些美味的菜肴。\nSaya dan keluarga ingin makan masakan sedap malam ini.",
                "2. 这家餐厅的汤非常美味，我下次还会来。\nSup di restoran ini sangat sedap, saya akan datang lagi.",
                "3. 这个蛋糕是自己做的，我觉得它美味极了。\nKuih ini saya buat sendiri, saya rasa ia sangat sedap."
            },
            true
        ));
    }
    
    /**
     * Get a curated dictionary entry by Malay word
     */
    public DictionaryEntry getEntryByMalayWord(String malayWord) {
        if (malayWord == null) return null;
        return DICTIONARY_ENTRIES.get(malayWord.toLowerCase());
    }
    
    /**
     * Get a curated dictionary entry by Mandarin word
     */
    public DictionaryEntry getEntryByMandarinWord(String mandarinWord) {
        if (mandarinWord == null) return null;
        for (DictionaryEntry entry : DICTIONARY_ENTRIES.values()) {
            if (entry.getMandarinWord().equals(mandarinWord)) {
                return entry;
            }
        }
        return null;
    }
    
    /**
     * Check if a curated entry exists for a Malay word
     */
    public boolean hasEntry(String malayWord) {
        return malayWord != null && DICTIONARY_ENTRIES.containsKey(malayWord.toLowerCase());
    }
    
    /**
     * Convert a DictionaryEntry to a DictionaryResponse
     */
    public DictionaryResponse convertToDictionaryResponse(DictionaryEntry entry, boolean fromMalay) {
        if (entry == null) return null;
        
        DictionaryResponse response = new DictionaryResponse();
        response.setMalayWord(entry.getMalayWord());
        response.setMandarinWord(entry.getMandarinWord());
        response.setPinyin(entry.getPronunciation());
        response.setExplanation(entry.getExplanation());
        
        // Join examples array into a string with newlines
        if (entry.getExamples() != null && entry.getExamples().length > 0) {
            response.setExamples(String.join("\n", entry.getExamples()));
        }
        
        response.setAdjective(entry.isAdjective());
        return response;
    }
    
    /**
     * Get all available Malay words with curated entries
     */
    public Set<String> getAllMalayWords() {
        return new HashSet<>(DICTIONARY_ENTRIES.keySet());
    }
    
    /**
     * Get pronunciation override for a word if exists
     */
    public String getPronunciationOverride(String malayWord) {
        if (malayWord == null) return null;
        Map<String, Object> override = WORD_OVERRIDES.get(malayWord.toLowerCase());
        if (override != null) {
            return (String) override.get("pronunciation");
        }
        return null;
    }
    
    /**
     * Get adjective flag override for a word if exists
     */
    public Boolean getAdjectiveOverride(String malayWord) {
        if (malayWord == null) return null;
        Map<String, Object> override = WORD_OVERRIDES.get(malayWord.toLowerCase());
        if (override != null) {
            return (Boolean) override.get("isAdjective");
        }
        return null;
    }
    
    /**
     * Check if a fallback entry exists for a word
     */
    public boolean hasFallbackEntry(String malayWord) {
        return malayWord != null && FALLBACK_ENTRIES.containsKey(malayWord.toLowerCase());
    }
    
    /**
     * Get fallback entry for a word
     */
    public DictionaryEntry getFallbackEntry(String malayWord) {
        if (malayWord == null) return null;
        return FALLBACK_ENTRIES.get(malayWord.toLowerCase());
    }
}
