package com.example.backend.service;

import com.example.backend.model.DictionaryResponse;
import org.springframework.stereotype.Service;
import java.util.*;

/**
 * DictionaryEntryService provides curated dictionary entries with explanations and pronunciations.
 * This service stores verified dictionary entries for specific Malay-Mandarin word pairs.
 */
@Service
public class DictionaryEntryService {
    
    // Stores curated dictionary entries with full details
    private static final Map<String, DictionaryEntry> DICTIONARY_ENTRIES = new HashMap<>();
    
    // Stores pronunciation and adjective overrides for specific words
    private static final Map<String, Map<String, Object>> WORD_OVERRIDES = new HashMap<>();
    
    public static class DictionaryEntry {
        private String malayWord;
        private String mandarinWord;
        private String pronunciation;
        private String explanation;
        private String[] examples;
        private boolean isAdjective;
        
        public DictionaryEntry(String malayWord, String mandarinWord, String pronunciation, 
                             String explanation, String[] examples, boolean isAdjective) {
            this.malayWord = malayWord;
            this.mandarinWord = mandarinWord;
            this.pronunciation = pronunciation;
            this.explanation = explanation;
            this.examples = examples;
            this.isAdjective = isAdjective;
        }
        
        // Getters
        public String getMalayWord() { return malayWord; }
        public String getMandarinWord() { return mandarinWord; }
        public String getPronunciation() { return pronunciation; }
        public String getExplanation() { return explanation; }
        public String[] getExamples() { return examples; }
        public boolean isAdjective() { return isAdjective; }
    }
    
    static {
        initializeDictionary();
    }
    
    private static void initializeDictionary() {
        // All words will be auto-generated by AI using LibreTranslate + DeepseekAI
        // No curated entries maintained
    }
    
    /**
     * Get a curated dictionary entry by Malay word
     */
    public DictionaryEntry getEntryByMalayWord(String malayWord) {
        if (malayWord == null) return null;
        return DICTIONARY_ENTRIES.get(malayWord.toLowerCase());
    }
    
    /**
     * Get a curated dictionary entry by Mandarin word
     */
    public DictionaryEntry getEntryByMandarinWord(String mandarinWord) {
        if (mandarinWord == null) return null;
        for (DictionaryEntry entry : DICTIONARY_ENTRIES.values()) {
            if (entry.getMandarinWord().equals(mandarinWord)) {
                return entry;
            }
        }
        return null;
    }
    
    /**
     * Check if a curated entry exists for a Malay word
     */
    public boolean hasEntry(String malayWord) {
        return malayWord != null && DICTIONARY_ENTRIES.containsKey(malayWord.toLowerCase());
    }
    
    /**
     * Convert a DictionaryEntry to a DictionaryResponse
     */
    public DictionaryResponse convertToDictionaryResponse(DictionaryEntry entry, boolean fromMalay) {
        if (entry == null) return null;
        
        DictionaryResponse response = new DictionaryResponse();
        response.setMalayWord(entry.getMalayWord());
        response.setMandarinWord(entry.getMandarinWord());
        response.setPinyin(entry.getPronunciation());
        response.setExplanation(entry.getExplanation());
        
        // Join examples array into a string with newlines
        if (entry.getExamples() != null && entry.getExamples().length > 0) {
            response.setExamples(String.join("\n", entry.getExamples()));
        }
        
        response.setAdjective(entry.isAdjective());
        return response;
    }
    
    /**
     * Get all available Malay words with curated entries
     */
    public Set<String> getAllMalayWords() {
        return new HashSet<>(DICTIONARY_ENTRIES.keySet());
    }
    
    /**
     * Get pronunciation override for a word if exists
     */
    public String getPronunciationOverride(String malayWord) {
        if (malayWord == null) return null;
        Map<String, Object> override = WORD_OVERRIDES.get(malayWord.toLowerCase());
        if (override != null) {
            return (String) override.get("pronunciation");
        }
        return null;
    }
    
    /**
     * Get adjective flag override for a word if exists
     */
    public Boolean getAdjectiveOverride(String malayWord) {
        if (malayWord == null) return null;
        Map<String, Object> override = WORD_OVERRIDES.get(malayWord.toLowerCase());
        if (override != null) {
            return (Boolean) override.get("isAdjective");
        }
        return null;
    }
}
